/// Filing types taken from this site
/// https://www.sec.gov/forms
#[derive(Debug, PartialEq)]
pub enum FilingType {
    _1,
    _10,
    _10D,
    _10K,
    _10M,
    _10Q,
    _11K,
    _12B25,
    _13F,
    _13H,
    _144,
    _15,
    _15F,
    _17H,
    _18,
    _18K,
    _19B4,
    _19B4E,
    _19B7,
    _1A,
    _1E,
    _1K,
    _1N,
    _1SA,
    _1U,
    _1Z,
    _20F,
    _24F2,
    _25,
    _2E,
    _3,
    _4,
    _40F,
    _5,
    _6K,
    _7M,
    _8A,
    _8K,
    _8M,
    _9M,
    ABS,
    ABS15G,
    ABSEE,
    ADV,
    ADVE,
    ADVH,
    ADVNR,
    ADVW,
    ATS,
    ATSN,
    ATSR,
    BD,
    BDW,
    BDN,
    C,
    CA1,
    CB,
    CFPORTAL,
    CRS,
    CUSTODY,
    D,
    F1,
    F10,
    F3,
    F4,
    F6,
    F7,
    F8,
    F80,
    FN,
    FX,
    ID,
    MA,
    MAI,
    MANR,
    MAW,
    MSD,
    MSDW,
    NRSRO,
    N14,
    N17D1,
    N17F1,
    N17F2,
    N18F1,
    N1A,
    N2,
    N23C3,
    N27D1,
    N3,
    N4,
    N5,
    N54A,
    N54C,
    N6,
    N6EI1,
    N6F,
    N8A,
    N8B2,
    N8B4,
    N8F,
    NCEN,
    NCR,
    NCSR,
    NMFP,
    NPORT,
    NPX,
    NQ,
    NRN,
    PF,
    PILOT,
    R31,
    SBSE,
    SBSEA,
    SBSEBD,
    SBSEC,
    SBSEW,
    SCI,
    SD,
    SDR,
    SE,
    SF1,
    SF3,
    SIP,
    S1,
    S11,
    S20,
    S3,
    S4,
    S6,
    S8,
    TA1,
    TA2,
    TAW,
    TCR,
    TH,
    T1,
    T2,
    T3,
    T4,
    T6,
    WBAPP,
    X17A19,
    X17A5,
    X17F1A,
}
pub struct Filing;
impl Filing {
    pub fn from_str(filing_type: &str) -> FilingType {
        match filing_type {
            "1" => FilingType::_1,
            "1-A" => FilingType::_10,
            "1-E" => FilingType::_10D,
            "1-K" => FilingType::_10K,
            "1-N" => FilingType::_10M,
            "1-SA" => FilingType::_10Q,
            "1-U" => FilingType::_11K,
            "1-Z" => FilingType::_12B25,
            "10" => FilingType::_13F,
            "10-D" => FilingType::_13H,
            "10-K" => FilingType::_144,
            "10-M" => FilingType::_15,
            "10-Q" => FilingType::_15F,
            "11-K" => FilingType::_17H,
            "12b-25" => FilingType::_18,
            "13F" => FilingType::_18K,
            "13H" => FilingType::_19B4,
            "144" => FilingType::_19B4E,
            "15" => FilingType::_19B7,
            "15F" => FilingType::_1A,
            "17-H" => FilingType::_1E,
            "18" => FilingType::_1K,
            "18-K" => FilingType::_1N,
            "19b-4" => FilingType::_1SA,
            "19b-4(e)" => FilingType::_1U,
            "19b-7" => FilingType::_1Z,
            "2-E" => FilingType::_20F,
            "20-F" => FilingType::_24F2,
            "24F-2" => FilingType::_25,
            "25" => FilingType::_2E,
            "3" => FilingType::_3,
            "4" => FilingType::_4,
            "40-F" => FilingType::_40F,
            "5" => FilingType::_5,
            "6-K" => FilingType::_6K,
            "7-M" => FilingType::_7M,
            "8-A" => FilingType::_8A,
            "8-K" => FilingType::_8K,
            "8-M" => FilingType::_8M,
            "9-M" => FilingType::_9M,
            "ABS" => FilingType::ABS,
            "ABS-15G" => FilingType::ABS15G,
            "ABS-EE" => FilingType::ABSEE,
            "ADV" => FilingType::ADV,
            "ADV-E" => FilingType::ADVE,
            "ADV-H" => FilingType::ADVH,
            "ADV-NR" => FilingType::ADVNR,
            "ADV-W" => FilingType::ADVW,
            "ATS" => FilingType::ATS,
            "ATS-N" => FilingType::ATSN,
            "ATS-R" => FilingType::ATSR,
            "BD" => FilingType::BD,
            "BD-N" => FilingType::BDW,
            "BDW" => FilingType::BDN,
            "C" => FilingType::C,
            "CA-1" => FilingType::CA1,
            "CB" => FilingType::CB,
            "CFPORTAL" => FilingType::CFPORTAL,
            "CRS" => FilingType::CRS,
            "CUSTODY" => FilingType::CUSTODY,
            "D" => FilingType::D,
            "F-1" => FilingType::F1,
            "F-10" => FilingType::F10,
            "F-3" => FilingType::F3,
            "F-4" => FilingType::F4,
            "F-6" => FilingType::F6,
            "F-7" => FilingType::F7,
            "F-8" => FilingType::F8,
            "F-80" => FilingType::F80,
            "F-N" => FilingType::FN,
            "F-X" => FilingType::FX,
            "ID" => FilingType::ID,
            "MA" => FilingType::MA,
            "MA-I" => FilingType::MAI,
            "MA-NR" => FilingType::MANR,
            "MA-W" => FilingType::MAW,
            "MSD" => FilingType::MSD,
            "MSDW" => FilingType::MSDW,
            "N-14" => FilingType::NRSRO,
            "N-17D-1" => FilingType::N14,
            "N-17f-1" => FilingType::N17D1,
            "N-17f-2" => FilingType::N17F1,
            "N-18f-1" => FilingType::N17F2,
            "N-1A" => FilingType::N18F1,
            "N-2" => FilingType::N1A,
            "N-23c-3" => FilingType::N2,
            "N-27D-1" => FilingType::N23C3,
            "N-3" => FilingType::N27D1,
            "N-4" => FilingType::N3,
            "N-5" => FilingType::N4,
            "N-54A" => FilingType::N5,
            "N-54C" => FilingType::N54A,
            "N-6" => FilingType::N54C,
            "N-6EI-1" => FilingType::N6,
            "N-6F" => FilingType::N6EI1,
            "N-8A" => FilingType::N6F,
            "N-8B-2" => FilingType::N8A,
            "N-8B-4" => FilingType::N8B2,
            "N-8F" => FilingType::N8B4,
            "N-CEN" => FilingType::N8F,
            "N-CR" => FilingType::NCEN,
            "N-CSR" => FilingType::NCR,
            "N-MFP" => FilingType::NCSR,
            "N-PORT" => FilingType::NMFP,
            "N-PX" => FilingType::NPORT,
            "N-Q" => FilingType::NPX,
            "N-RN" => FilingType::NQ,
            "NRSRO" => FilingType::NRN,
            "PF" => FilingType::PF,
            "PILOT" => FilingType::PILOT,
            "R31" => FilingType::R31,
            "S-1" => FilingType::SBSE,
            "S-11" => FilingType::SBSEA,
            "S-20" => FilingType::SBSEBD,
            "S-3" => FilingType::SBSEC,
            "S-4" => FilingType::SBSEW,
            "S-6" => FilingType::SCI,
            "S-8" => FilingType::SD,
            "SBSE" => FilingType::SDR,
            "SBSE-A" => FilingType::SE,
            "SBSE-BD" => FilingType::SF1,
            "SBSE-C" => FilingType::SF3,
            "SBSE-W" => FilingType::SIP,
            "SCI" => FilingType::S1,
            "SD" => FilingType::S11,
            "SDR" => FilingType::S20,
            "SE" => FilingType::S3,
            "SF-1" => FilingType::S4,
            "SF-3" => FilingType::S6,
            "SIP" => FilingType::S8,
            "T-1" => FilingType::TA1,
            "T-2" => FilingType::TA2,
            "T-3" => FilingType::TAW,
            "T-4" => FilingType::TCR,
            "T-6" => FilingType::TH,
            "TA-1" => FilingType::T1,
            "TA-2" => FilingType::T2,
            "TA-W" => FilingType::T3,
            "TCR" => FilingType::T4,
            "TH" => FilingType::T6,
            "WB-APP" => FilingType::WBAPP,
            "X-17A-19" => FilingType::X17A19,
            "X-17A-5" => FilingType::X17A5,
            "X-17F-1A" => FilingType::X17F1A,
            _ => panic!("Filing type does not exist"),
        }
    }
    pub fn to_string(filing_type: FilingType) -> String {
        match filing_type {
            FilingType::_1 => "1".to_string(),
            FilingType::_10 => "1-A".to_string(),
            FilingType::_10D => "1-E".to_string(),
            FilingType::_10K => "1-K".to_string(),
            FilingType::_10M => "1-N".to_string(),
            FilingType::_10Q => "1-SA".to_string(),
            FilingType::_11K => "1-U".to_string(),
            FilingType::_12B25 => "1-Z".to_string(),
            FilingType::_13F => "10".to_string(),
            FilingType::_13H => "10-D".to_string(),
            FilingType::_144 => "10-K".to_string(),
            FilingType::_15 => "10-M".to_string(),
            FilingType::_15F => "10-Q".to_string(),
            FilingType::_17H => "11-K".to_string(),
            FilingType::_18 => "12b-25".to_string(),
            FilingType::_18K => "13F".to_string(),
            FilingType::_19B4 => "13H".to_string(),
            FilingType::_19B4E => "144".to_string(),
            FilingType::_19B7 => "15".to_string(),
            FilingType::_1A => "15F".to_string(),
            FilingType::_1E => "17-H".to_string(),
            FilingType::_1K => "18".to_string(),
            FilingType::_1N => "18-K".to_string(),
            FilingType::_1SA => "19b-4".to_string(),
            FilingType::_1U => "19b-4(e)".to_string(),
            FilingType::_1Z => "19b-7".to_string(),
            FilingType::_20F => "2-E".to_string(),
            FilingType::_24F2 => "20-F".to_string(),
            FilingType::_25 => "24F-2".to_string(),
            FilingType::_2E => "25".to_string(),
            FilingType::_3 => "3".to_string(),
            FilingType::_4 => "4".to_string(),
            FilingType::_40F => "40-F".to_string(),
            FilingType::_5 => "5".to_string(),
            FilingType::_6K => "6-K".to_string(),
            FilingType::_7M => "7-M".to_string(),
            FilingType::_8A => "8-A".to_string(),
            FilingType::_8K => "8-K".to_string(),
            FilingType::_8M => "8-M".to_string(),
            FilingType::_9M => "9-M".to_string(),
            FilingType::ABS => "ABS".to_string(),
            FilingType::ABS15G => "ABS-15G".to_string(),
            FilingType::ABSEE => "ABS-EE".to_string(),
            FilingType::ADV => "ADV".to_string(),
            FilingType::ADVE => "ADV-E".to_string(),
            FilingType::ADVH => "ADV-H".to_string(),
            FilingType::ADVNR => "ADV-NR".to_string(),
            FilingType::ADVW => "ADV-W".to_string(),
            FilingType::ATS => "ATS".to_string(),
            FilingType::ATSN => "ATS-N".to_string(),
            FilingType::ATSR => "ATS-R".to_string(),
            FilingType::BD => "BD".to_string(),
            FilingType::BDW => "BD-N".to_string(),
            FilingType::BDN => "BDW".to_string(),
            FilingType::C => "C".to_string(),
            FilingType::CA1 => "CA-1".to_string(),
            FilingType::CB => "CB".to_string(),
            FilingType::CFPORTAL => "CFPORTAL".to_string(),
            FilingType::CRS => "CRS".to_string(),
            FilingType::CUSTODY => "CUSTODY".to_string(),
            FilingType::D => "D".to_string(),
            FilingType::F1 => "F-1".to_string(),
            FilingType::F10 => "F-10".to_string(),
            FilingType::F3 => "F-3".to_string(),
            FilingType::F4 => "F-4".to_string(),
            FilingType::F6 => "F-6".to_string(),
            FilingType::F7 => "F-7".to_string(),
            FilingType::F8 => "F-8".to_string(),
            FilingType::F80 => "F-80".to_string(),
            FilingType::FN => "F-N".to_string(),
            FilingType::FX => "F-X".to_string(),
            FilingType::ID => "ID".to_string(),
            FilingType::MA => "MA".to_string(),
            FilingType::MAI => "MA-I".to_string(),
            FilingType::MANR => "MA-NR".to_string(),
            FilingType::MAW => "MA-W".to_string(),
            FilingType::MSD => "MSD".to_string(),
            FilingType::MSDW => "MSDW".to_string(),
            FilingType::NRSRO => "N-14".to_string(),
            FilingType::N14 => "N-17D-1".to_string(),
            FilingType::N17D1 => "N-17f-1".to_string(),
            FilingType::N17F1 => "N-17f-2".to_string(),
            FilingType::N17F2 => "N-18f-1".to_string(),
            FilingType::N18F1 => "N-1A".to_string(),
            FilingType::N1A => "N-2".to_string(),
            FilingType::N2 => "N-23c-3".to_string(),
            FilingType::N23C3 => "N-27D-1".to_string(),
            FilingType::N27D1 => "N-3".to_string(),
            FilingType::N3 => "N-4".to_string(),
            FilingType::N4 => "N-5".to_string(),
            FilingType::N5 => "N-54A".to_string(),
            FilingType::N54A => "N-54C".to_string(),
            FilingType::N54C => "N-6".to_string(),
            FilingType::N6 => "N-6EI-1".to_string(),
            FilingType::N6EI1 => "N-6F".to_string(),
            FilingType::N6F => "N-8A".to_string(),
            FilingType::N8A => "N-8B-2".to_string(),
            FilingType::N8B2 => "N-8B-4".to_string(),
            FilingType::N8B4 => "N-8F".to_string(),
            FilingType::N8F => "N-CEN".to_string(),
            FilingType::NCEN => "N-CR".to_string(),
            FilingType::NCR => "N-CSR".to_string(),
            FilingType::NCSR => "N-MFP".to_string(),
            FilingType::NMFP => "N-PORT".to_string(),
            FilingType::NPORT => "N-PX".to_string(),
            FilingType::NPX => "N-Q".to_string(),
            FilingType::NQ => "N-RN".to_string(),
            FilingType::NRN => "NRSRO".to_string(),
            FilingType::PF => "PF".to_string(),
            FilingType::PILOT => "PILOT".to_string(),
            FilingType::R31 => "R31".to_string(),
            FilingType::SBSE => "S-1".to_string(),
            FilingType::SBSEA => "S-11".to_string(),
            FilingType::SBSEBD => "S-20".to_string(),
            FilingType::SBSEC => "S-3".to_string(),
            FilingType::SBSEW => "S-4".to_string(),
            FilingType::SCI => "S-6".to_string(),
            FilingType::SD => "S-8".to_string(),
            FilingType::SDR => "SBSE".to_string(),
            FilingType::SE => "SBSE-A".to_string(),
            FilingType::SF1 => "SBSE-BD".to_string(),
            FilingType::SF3 => "SBSE-C".to_string(),
            FilingType::SIP => "SBSE-W".to_string(),
            FilingType::S1 => "SCI".to_string(),
            FilingType::S11 => "SD".to_string(),
            FilingType::S20 => "SDR".to_string(),
            FilingType::S3 => "SE".to_string(),
            FilingType::S4 => "SF-1".to_string(),
            FilingType::S6 => "SF-3".to_string(),
            FilingType::S8 => "SIP".to_string(),
            FilingType::TA1 => "T-1".to_string(),
            FilingType::TA2 => "T-2".to_string(),
            FilingType::TAW => "T-3".to_string(),
            FilingType::TCR => "T-4".to_string(),
            FilingType::TH => "T-6".to_string(),
            FilingType::T1 => "TA-1".to_string(),
            FilingType::T2 => "TA-2".to_string(),
            FilingType::T3 => "TA-W".to_string(),
            FilingType::T4 => "TCR".to_string(),
            FilingType::T6 => "TH".to_string(),
            FilingType::WBAPP => "WB-APP".to_string(),
            FilingType::X17A19 => "X-17A-19".to_string(),
            FilingType::X17A5 => "X-17A-5".to_string(),
            FilingType::X17F1A => "X-17F-1A".to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_valid_filing_type_from_str() {
        assert_eq!(Filing::from_str("X-17F-1A"), FilingType::X17F1A)
    }
    #[test]
    #[should_panic]
    fn test_invalid_filing_type_from_str() {
        let _unused = Filing::from_str("not a real filing type");
        assert!(false)
    }
    #[test]
    fn test_filing_type_to_string() {
        assert_eq!(Filing::to_string(FilingType::X17F1A), "X-17F-1A".to_string())
    }
}
